---
autogenerated: false
title: NIDAQ
redirect_from: /wiki/NIDAQ
layout: page
---

## Adapter for National Instruments DAQ with analog and digital outputs

<table>
<tr>
<td markdown="1">

**Summary:**

</td>
<td markdown="1">

Controls NI I/O boards through NI-DAQmx interface. Supports simultaneous
hardware sequencing using multiple analog and digital output ports.
Based on the NIMultiAnalog adapter.  Replaces both the NIMultiAnalog 
and NI100x adpaters.

</td>
</tr>
<tr>
<td markdown="1">

**Author:**

</td>
<td markdown="1">

Nico Stuurman, Altos Labs.  Based on NIMultiAnalog code by Mark Tsuchida, Open Imaging, Inc.

</td>
</tr>
<tr>
<td markdown="1">

**License:**

</td>
<td markdown="1">

LGPL

</td>
</tr>
<tr>
<td markdown="1">

**Platforms:**

</td>
<td markdown="1">

Windows only

</td>
</tr>
</table>

See also: [NI100X](National_Instruments) and [NIMultiAnalog](NiMultiAnalog).

This device adapter is intended for use with National Instruments DAQ
boards/boxes that have multiple analog and/or digital output ports.  
It supports hardware triggering of analog and digital output transitions,
as well as balnking of digital outputs.  However, it does so through 
different mechanisms, and uses capabilities that are not present on all
NIDAQ equipment.  Digital output sequencing (and blanking) use a feature 
named `ChangeDetection`.  A list of NIDAQ devics that support ChangeDetection
can be found [here](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z000000PAqXSAW&l=en-US).

To use ChangeDetection, the input pin needs to be part of the port 
that it controls.  Therefore, if a port supports ChangeDetection, this
Micro-Manager device adapter reserves the last pin of that port (i.e. 
p0.7 for the first 8 pin port of a given Dev) for input. To hardware 
trigger an analog output port, however, the pinput pin needs to be 
one of the PFI pins (selectable in the hub device).  Therefore, if you 
want to control both analog and digital outputs with the same input
trigger, you will need to physicall connect these two pins (for instance,
run a wire between p0.7 and PFI0).

The hardware triggering support is flexible enough that you can use the
same DAQ to control a piezo Z stage, the illumination channel (either 
using analog output ports as TTL outputs, with the DATTLStateDevice
available in [Utilities](Utilities), or directly with digital output ports), 
and illumination intensities simultaneously. In such a configuration, both the Z stage
and the illumination channel can be sequenced by hardware triggering at
the same time in an MDA.



