# Generated by Configurator on Fri Nov 30 16:14:04 JST 2018

# Reset
Property,Core,Initialize,0

# Devices
Device,COM4,SerialManager,COM4
Device,ChuoSeiki XY Controller,ChuoSeiki_MD5000,ChuoSeiki XY Controller
Device,FakeCamera,FakeCamera,FakeCamera

# Pre-init settings for devices
Property,COM4,AnswerTimeout,500.0000
Property,COM4,BaudRate,115200
Property,COM4,DataBits,8
Property,COM4,DelayBetweenCharsMs,0.0000
Property,COM4,Fast USB to Serial,Disable
Property,COM4,Handshaking,Off
Property,COM4,Parity,None
Property,COM4,StopBits,1
Property,COM4,Verbose,1
Property,ChuoSeiki XY Controller,Port,COM4

# Pre-init settings for COM ports

# Hub (parent) references

# Initialize
Property,Core,Initialize,1

# Delays

# Focus directions

# Roles
Property,Core,Camera,FakeCamera
Property,Core,AutoShutter,1

# Camera-synchronized devices

# Labels

# Configuration presets
# Group: Group 1 - XY stage setting
# Preset: Speed2 1000pps
ConfigGroup,Group 1 - XY stage setting,Speed2 1000pps,ChuoSeiki XY Controller,X Accel. pattern,2.0000
ConfigGroup,Group 1 - XY stage setting,Speed2 1000pps,ChuoSeiki XY Controller,X Speed,1000.0000
ConfigGroup,Group 1 - XY stage setting,Speed2 1000pps,ChuoSeiki XY Controller,X Step Size,1.0000
ConfigGroup,Group 1 - XY stage setting,Speed2 1000pps,ChuoSeiki XY Controller,Y Accel. pattern,2.0000
ConfigGroup,Group 1 - XY stage setting,Speed2 1000pps,ChuoSeiki XY Controller,Y Speed,1000.0000
ConfigGroup,Group 1 - XY stage setting,Speed2 1000pps,ChuoSeiki XY Controller,Y Step Size,1.0000
ConfigGroup,Group 1 - XY stage setting,Speed2 1000pps,ChuoSeiki XY Controller,TransposeMirrorX,0
ConfigGroup,Group 1 - XY stage setting,Speed2 1000pps,ChuoSeiki XY Controller,TransposeMirrorY,0

# Preset: Speed3 2000pps
ConfigGroup,Group 1 - XY stage setting,Speed3 2000pps,ChuoSeiki XY Controller,TransposeMirrorX,0
ConfigGroup,Group 1 - XY stage setting,Speed3 2000pps,ChuoSeiki XY Controller,TransposeMirrorY,0
ConfigGroup,Group 1 - XY stage setting,Speed3 2000pps,ChuoSeiki XY Controller,X Accel. pattern,2.0000
ConfigGroup,Group 1 - XY stage setting,Speed3 2000pps,ChuoSeiki XY Controller,X Speed,2000.0000
ConfigGroup,Group 1 - XY stage setting,Speed3 2000pps,ChuoSeiki XY Controller,X Step Size,1.0000
ConfigGroup,Group 1 - XY stage setting,Speed3 2000pps,ChuoSeiki XY Controller,Y Accel. pattern,2.0000
ConfigGroup,Group 1 - XY stage setting,Speed3 2000pps,ChuoSeiki XY Controller,Y Speed,2000.0000
ConfigGroup,Group 1 - XY stage setting,Speed3 2000pps,ChuoSeiki XY Controller,Y Step Size,1.0000

# Preset: Speed5 8000pps
ConfigGroup,Group 1 - XY stage setting,Speed5 8000pps,ChuoSeiki XY Controller,X Accel. pattern,2.0000
ConfigGroup,Group 1 - XY stage setting,Speed5 8000pps,ChuoSeiki XY Controller,X Speed,8000.0000
ConfigGroup,Group 1 - XY stage setting,Speed5 8000pps,ChuoSeiki XY Controller,X Step Size,1.0000
ConfigGroup,Group 1 - XY stage setting,Speed5 8000pps,ChuoSeiki XY Controller,Y Accel. pattern,2.0000
ConfigGroup,Group 1 - XY stage setting,Speed5 8000pps,ChuoSeiki XY Controller,Y Speed,8000.0000
ConfigGroup,Group 1 - XY stage setting,Speed5 8000pps,ChuoSeiki XY Controller,Y Step Size,1.0000
ConfigGroup,Group 1 - XY stage setting,Speed5 8000pps,ChuoSeiki XY Controller,TransposeMirrorX,0
ConfigGroup,Group 1 - XY stage setting,Speed5 8000pps,ChuoSeiki XY Controller,TransposeMirrorY,0

# Preset: Speed4 4000pps
ConfigGroup,Group 1 - XY stage setting,Speed4 4000pps,ChuoSeiki XY Controller,X Accel. pattern,2.0000
ConfigGroup,Group 1 - XY stage setting,Speed4 4000pps,ChuoSeiki XY Controller,X Speed,4000.0000
ConfigGroup,Group 1 - XY stage setting,Speed4 4000pps,ChuoSeiki XY Controller,X Step Size,1.0000
ConfigGroup,Group 1 - XY stage setting,Speed4 4000pps,ChuoSeiki XY Controller,Y Accel. pattern,2.0000
ConfigGroup,Group 1 - XY stage setting,Speed4 4000pps,ChuoSeiki XY Controller,Y Speed,4000.0000
ConfigGroup,Group 1 - XY stage setting,Speed4 4000pps,ChuoSeiki XY Controller,Y Step Size,1.0000
ConfigGroup,Group 1 - XY stage setting,Speed4 4000pps,ChuoSeiki XY Controller,TransposeMirrorX,0
ConfigGroup,Group 1 - XY stage setting,Speed4 4000pps,ChuoSeiki XY Controller,TransposeMirrorY,0

# Preset: Speed1 500pps
ConfigGroup,Group 1 - XY stage setting,Speed1 500pps,ChuoSeiki XY Controller,TransposeMirrorX,0
ConfigGroup,Group 1 - XY stage setting,Speed1 500pps,ChuoSeiki XY Controller,TransposeMirrorY,0
ConfigGroup,Group 1 - XY stage setting,Speed1 500pps,ChuoSeiki XY Controller,X Accel. pattern,2.0000
ConfigGroup,Group 1 - XY stage setting,Speed1 500pps,ChuoSeiki XY Controller,X Speed,500.0000
ConfigGroup,Group 1 - XY stage setting,Speed1 500pps,ChuoSeiki XY Controller,X Step Size,1.0000
ConfigGroup,Group 1 - XY stage setting,Speed1 500pps,ChuoSeiki XY Controller,Y Accel. pattern,2.0000
ConfigGroup,Group 1 - XY stage setting,Speed1 500pps,ChuoSeiki XY Controller,Y Speed,500.0000
ConfigGroup,Group 1 - XY stage setting,Speed1 500pps,ChuoSeiki XY Controller,Y Step Size,1.0000



# PixelSize settings
